-- V17__Implement_Withdrawal_Policy.sql

-- 1. 탈퇴 기록(WithdrawalHistory) 테이블 생성 (재가입 방지용)
CREATE TABLE withdrawal_history (
                                    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    oauth_provider VARCHAR(50) NOT NULL,
                                    oauth_id VARCHAR(255) NOT NULL,
                                    email VARCHAR(255),
                                    withdrawn_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                    PRIMARY KEY (history_id)
);

-- 중복 방지 제약조건
ALTER TABLE withdrawal_history
    ADD CONSTRAINT uq_withdrawal_history_oauth UNIQUE (oauth_provider, oauth_id);

-- 2. User 테이블에서 논리 삭제 컬럼 제거 (물리 삭제 전환)
ALTER TABLE "User" DROP COLUMN IF EXISTS "DELETED_AT";

-- =========================================================
-- [전략 1] CASCADE: 유저 삭제 시 같이 지워질 데이터들
-- =========================================================

-- (1) MemberProfile
ALTER TABLE "MemberProfile" DROP CONSTRAINT IF EXISTS "FK_MemberProfile_User";
ALTER TABLE "MemberProfile" ADD CONSTRAINT "FK_MemberProfile_User_Cascade" FOREIGN KEY ("USER_ID") REFERENCES "User" ("USER_ID") ON DELETE CASCADE;

-- (2) RefreshTokens
ALTER TABLE "RefreshTokens" DROP CONSTRAINT IF EXISTS "FK_RefreshTokens_User";
ALTER TABLE "RefreshTokens" ADD CONSTRAINT "FK_RefreshTokens_User_Cascade" FOREIGN KEY ("USER_ID") REFERENCES "User" ("USER_ID") ON DELETE CASCADE;

-- (3) JoinApplication (가입 신청서)
ALTER TABLE "JoinApplication" DROP CONSTRAINT IF EXISTS "FK_JoinApplication_User";
ALTER TABLE "JoinApplication" ADD CONSTRAINT "FK_JoinApplication_User_Cascade" FOREIGN KEY ("USER_ID") REFERENCES "User" ("USER_ID") ON DELETE CASCADE;

-- (4) Notification (알림)
ALTER TABLE "Notification" DROP CONSTRAINT IF EXISTS "FK_Notification_User";
ALTER TABLE "Notification" ADD CONSTRAINT "FK_Notification_User_Cascade" FOREIGN KEY ("USER_ID") REFERENCES "User" ("USER_ID") ON DELETE CASCADE;

-- (5) Post (게시글) - 개인정보 파기 원칙 우선
ALTER TABLE "Post" DROP CONSTRAINT IF EXISTS "FK_Post_User";
ALTER TABLE "Post" ADD CONSTRAINT "FK_Post_User_Cascade" FOREIGN KEY ("USER_ID") REFERENCES "User" ("USER_ID") ON DELETE CASCADE;

-- (6) Comment (댓글)
ALTER TABLE "Comment" DROP CONSTRAINT IF EXISTS "FK_Comment_User";
ALTER TABLE "Comment" ADD CONSTRAINT "FK_Comment_User_Cascade" FOREIGN KEY ("USER_ID") REFERENCES "User" ("USER_ID") ON DELETE CASCADE;


-- =========================================================
-- [전략 2] SET NULL: 유저 삭제 시 데이터는 남기고 작성자만 NULL 처리
-- =========================================================

-- (1) Donation (후원) - 법적 보관
ALTER TABLE "Donation" ALTER COLUMN "USER_ID" DROP NOT NULL;
ALTER TABLE "Donation" DROP CONSTRAINT IF EXISTS "FK_Donation_User";
ALTER TABLE "Donation" ADD CONSTRAINT "FK_Donation_User_SetNull" FOREIGN KEY ("USER_ID") REFERENCES "User" ("USER_ID") ON DELETE SET NULL;

-- (2) Notice (공지사항) - 단체 자산
ALTER TABLE "Notice" ALTER COLUMN "USER_ID" DROP NOT NULL;
ALTER TABLE "Notice" DROP CONSTRAINT IF EXISTS "FK_Notice_User";
ALTER TABLE "Notice" ADD CONSTRAINT "FK_Notice_User_SetNull" FOREIGN KEY ("USER_ID") REFERENCES "User" ("USER_ID") ON DELETE SET NULL;

-- (3) Sheet (악보) - 단체 자산
ALTER TABLE "Sheet" ALTER COLUMN "USER_ID" DROP NOT NULL;
ALTER TABLE "Sheet" DROP CONSTRAINT IF EXISTS "FK_Sheet_User";
ALTER TABLE "Sheet" ADD CONSTRAINT "FK_Sheet_User_SetNull" FOREIGN KEY ("USER_ID") REFERENCES "User" ("USER_ID") ON DELETE SET NULL;

-- (4) ActivityMaterial (활동자료) - 단체 자산
ALTER TABLE "ActivityMaterial" ALTER COLUMN "USER_ID" DROP NOT NULL;
ALTER TABLE "ActivityMaterial" DROP CONSTRAINT IF EXISTS "FK_ActivityMaterial_User";
ALTER TABLE "ActivityMaterial" ADD CONSTRAINT "FK_ActivityMaterial_User_SetNull" FOREIGN KEY ("USER_ID") REFERENCES "User" ("USER_ID") ON DELETE SET NULL;

-- (5) Gallery (갤러리) - 단체 자산
ALTER TABLE "Gallery" ALTER COLUMN "USER_ID" DROP NOT NULL;
ALTER TABLE "Gallery" DROP CONSTRAINT IF EXISTS "FK_Gallery_User";
ALTER TABLE "Gallery" ADD CONSTRAINT "FK_Gallery_User_SetNull" FOREIGN KEY ("USER_ID") REFERENCES "User" ("USER_ID") ON DELETE SET NULL;