-- 1. User (사용자) 테이블
CREATE TABLE "User"
(
    "USER_ID"           BIGSERIAL    NOT NULL,
    "OAUTH_PROVIDER"    VARCHAR(50)  NOT NULL,
    "OAUTH_ID"          VARCHAR(255) NOT NULL,
    "EMAIL"             VARCHAR(255) NULL,
    "NAME"              VARCHAR(100) NOT NULL,
    "PROFILE_IMAGE_KEY" VARCHAR(255) NULL,
    "ROLE"              VARCHAR(20)  NOT NULL DEFAULT 'USER' CHECK ("ROLE" IN ('USER', 'MEMBER', 'ADMIN')),
    "CREATED_AT"        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT"        TIMESTAMPTZ NULL,
    "DELETED_AT"        TIMESTAMPTZ NULL,
    PRIMARY KEY ("USER_ID"),
    UNIQUE ("OAUTH_PROVIDER", "OAUTH_ID"),
    UNIQUE ("EMAIL")
);

-- 2. MemberProfile (단원 프로필) 테이블
CREATE TABLE "MemberProfile"
(
    "USER_ID"           BIGINT       NOT NULL,
    "PART"              VARCHAR(100) NOT NULL DEFAULT 'NONE',
    "INTERESTS"         VARCHAR(255) NULL,
    "MY_DREAM"          TEXT NULL,
    "HASH_TAGS"         VARCHAR(255) NULL,
    "PROFILE_IMAGE_KEY" VARCHAR(255) NULL,
    "IS_PUBLIC"         BOOLEAN      NOT NULL DEFAULT TRUE,
    "UPDATED_AT"        TIMESTAMPTZ NULL,
    PRIMARY KEY ("USER_ID"),
    CONSTRAINT "FK_User_TO_MemberProfile" FOREIGN KEY ("USER_ID")
        REFERENCES "User" ("USER_ID") ON DELETE CASCADE
);

-- 3. JoinApplication (단원 가입 신청) 테이블
CREATE TABLE "JoinApplication"
(
    "JOIN_ID"    BIGSERIAL    NOT NULL,
    "USER_ID"    BIGINT       NOT NULL,
    "PART"       VARCHAR(100) NOT NULL,
    "INTERESTS"  VARCHAR(255) NULL,
    "MY_DREAM"   TEXT NULL,
    "HASH_TAGS"  VARCHAR(255) NULL,
    "STATUS"     VARCHAR(20)  NOT NULL DEFAULT 'PENDING' CHECK ("STATUS" IN ('PENDING', 'APPROVED', 'REJECTED')),
    "CREATED_AT" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("JOIN_ID"),
    CONSTRAINT "FK_User_TO_JoinApplication" FOREIGN KEY ("USER_ID")
        REFERENCES "User" ("USER_ID")
);

-- 4. History (연혁) 테이블
CREATE TABLE "History"
(
    "HISTORY_ID" BIGSERIAL   NOT NULL,
    "YEAR"       INTEGER     NOT NULL,
    "CONTENT"    TEXT        NOT NULL,
    "CREATED_AT" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("HISTORY_ID")
);

-- 5. PerformanceSchedule (공연 일정) 테이블
CREATE TABLE "PerformanceSchedule"
(
    "PERFORMANCE_ID" BIGSERIAL    NOT NULL,
    "TITLE"          VARCHAR(200) NOT NULL,
    "DATE"           TIMESTAMPTZ  NOT NULL,
    "LOCATION"       VARCHAR(200) NOT NULL,
    "DESCRIPTION"    TEXT NULL,
    "TICKET_LINK"    VARCHAR(255) NULL,
    "CREATED_AT"     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT"     TIMESTAMPTZ NULL,
    "DELETED_AT"     TIMESTAMPTZ NULL,
    PRIMARY KEY ("PERFORMANCE_ID")
);

-- 6. Guestbook (방명록) 테이블
CREATE TABLE "Guestbook"
(
    "GUESTBOOK_ID" BIGSERIAL    NOT NULL,
    "NAME"         VARCHAR(100) NOT NULL,
    "CONTENT"      TEXT         NOT NULL,
    "PASSWORD"     VARCHAR(255) NULL,
    "IP_ADDRESS"   VARCHAR(50)  NULL,
    "STATUS"       VARCHAR(20)  NOT NULL DEFAULT 'HIDDEN' CHECK ("STATUS" IN ('APPROVED', 'HIDDEN')),
    "CREATED_AT"   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT"   TIMESTAMPTZ  NULL,
    "DELETED_AT"   TIMESTAMPTZ  NULL,
    PRIMARY KEY ("GUESTBOOK_ID")
);

-- 7. Inquiry (문의) 테이블
CREATE TABLE "Inquiry"
(
    "INQUIRY_ID"  BIGSERIAL    NOT NULL,
    "NAME"        VARCHAR(100) NOT NULL,
    "EMAIL"       VARCHAR(255) NOT NULL,
    "CONTENT"     TEXT         NOT NULL,
    "STATUS"      VARCHAR(20)  NOT NULL DEFAULT 'PENDING' CHECK ("STATUS" IN ('PENDING', 'ANSWERED')),
    "ANSWER"      TEXT NULL,
    "CREATED_AT"  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ANSWERED_AT" TIMESTAMPTZ NULL,
    PRIMARY KEY ("INQUIRY_ID")
);

-- 8. Faq (자주묻는질문) 테이블
CREATE TABLE "Faq"
(
    "FAQ_ID"     BIGSERIAL   NOT NULL,
    "QUESTION"   TEXT        NOT NULL,
    "ANSWER"     TEXT        NOT NULL,
    "CREATED_AT" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMPTZ NULL,
    PRIMARY KEY ("FAQ_ID")
);

-- 9. Banner (배너) 테이블
CREATE TABLE "Banner"
(
    "BANNER_ID"   BIGSERIAL    NOT NULL,
    "IMAGE_KEY"   VARCHAR(255) NOT NULL,
    "IMAGE_NAME"  VARCHAR(200) NOT NULL,
    "TITLE"       VARCHAR(200) NULL,
    "DESCRIPTION" TEXT NULL,
    "IS_ACTIVE"   BOOLEAN      NOT NULL DEFAULT TRUE,
    "CREATED_AT"  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT"  TIMESTAMPTZ NULL,
    "DELETED_AT"  TIMESTAMPTZ NULL,
    PRIMARY KEY ("BANNER_ID"),
    UNIQUE ("IMAGE_KEY")
);

-- 10. Post (자유게시판) 테이블
CREATE TABLE "Post"
(
    "POST_ID"    BIGSERIAL    NOT NULL,
    "USER_ID"    BIGINT       NOT NULL,
    "TITLE"      VARCHAR(200) NOT NULL,
    "CONTENT"    TEXT         NOT NULL,
    "CREATED_AT" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMPTZ NULL,
    "DELETED_AT" TIMESTAMPTZ NULL,
    PRIMARY KEY ("POST_ID"),
    CONSTRAINT "FK_User_TO_Post" FOREIGN KEY ("USER_ID")
        REFERENCES "User" ("USER_ID")
);

-- 11. Comment (댓글) 테이블
CREATE TABLE "Comment"
(
    "COMMENT_ID" BIGSERIAL   NOT NULL,
    "POST_ID"    BIGINT      NOT NULL,
    "USER_ID"    BIGINT      NOT NULL,
    "CONTENT"    TEXT        NOT NULL,
    "CREATED_AT" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DELETED_AT" TIMESTAMPTZ NULL,
    PRIMARY KEY ("COMMENT_ID"),
    CONSTRAINT "FK_Post_TO_Comment" FOREIGN KEY ("POST_ID")
        REFERENCES "Post" ("POST_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_User_TO_Comment" FOREIGN KEY ("USER_ID")
        REFERENCES "User" ("USER_ID")
);

-- 12. PostImage (게시글 이미지) 테이블
CREATE TABLE "PostImage"
(
    "IMAGE_ID"   BIGSERIAL    NOT NULL,
    "POST_ID"    BIGINT       NOT NULL,
    "IMAGE_KEY"  VARCHAR(255) NOT NULL,
    "IMAGE_NAME" VARCHAR(200) NOT NULL,
    "CREATED_AT" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("IMAGE_ID"),
    UNIQUE ("IMAGE_KEY"),
    CONSTRAINT "FK_Post_TO_PostImage" FOREIGN KEY ("POST_ID")
        REFERENCES "Post" ("POST_ID") ON DELETE CASCADE
);

-- 13. Notice (공지사항) 테이블
CREATE TABLE "Notice"
(
    "NOTICE_ID"  BIGSERIAL    NOT NULL,
    "USER_ID"    BIGINT       NOT NULL,
    "TITLE"      VARCHAR(200) NOT NULL,
    "CONTENT"    TEXT         NOT NULL,
    "CREATED_AT" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMPTZ NULL,
    "DELETED_AT" TIMESTAMPTZ NULL,
    PRIMARY KEY ("NOTICE_ID"),
    CONSTRAINT "FK_User_TO_Notice" FOREIGN KEY ("USER_ID")
        REFERENCES "User" ("USER_ID")
);

-- 14. NoticeImage (공지사항 이미지) 테이블
CREATE TABLE "NoticeImage"
(
    "IMAGE_ID"   BIGSERIAL    NOT NULL,
    "NOTICE_ID"  BIGINT       NOT NULL,
    "IMAGE_KEY"  VARCHAR(255) NOT NULL,
    "IMAGE_NAME" VARCHAR(200) NOT NULL,
    "CREATED_AT" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("IMAGE_ID"),
    UNIQUE ("IMAGE_KEY"),
    CONSTRAINT "FK_Notice_TO_NoticeImage" FOREIGN KEY ("NOTICE_ID")
        REFERENCES "Notice" ("NOTICE_ID") ON DELETE CASCADE
);

-- 15. Gallery (갤러리) 테이블
CREATE TABLE "Gallery"
(
    "GALLERY_ID"  BIGSERIAL    NOT NULL,
    "USER_ID"     BIGINT       NOT NULL,
    "TYPE"        VARCHAR(50)  NOT NULL,
    "TITLE"       VARCHAR(200) NOT NULL,
    "DESCRIPTION" TEXT NULL,
    "CREATED_AT"  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT"  TIMESTAMPTZ NULL,
    "DELETED_AT"  TIMESTAMPTZ NULL,
    PRIMARY KEY ("GALLERY_ID"),
    CONSTRAINT "FK_User_TO_Gallery" FOREIGN KEY ("USER_ID")
        REFERENCES "User" ("USER_ID")
);

-- 16. GalleryMedia (갤러리 미디어) 테이블
CREATE TABLE "GalleryMedia"
(
    "MEDIA_ID"   BIGSERIAL    NOT NULL,
    "GALLERY_ID" BIGINT       NOT NULL,
    "FILE_KEY"   VARCHAR(255) NOT NULL,
    "FILE_NAME"  VARCHAR(200) NOT NULL,
    "MEDIA_TYPE" VARCHAR(20)  NOT NULL CHECK ("MEDIA_TYPE" IN ('IMAGE', 'VIDEO')),
    "CREATED_AT" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("MEDIA_ID"),
    UNIQUE ("FILE_KEY"),
    CONSTRAINT "FK_Gallery_TO_GalleryMedia" FOREIGN KEY ("GALLERY_ID")
        REFERENCES "Gallery" ("GALLERY_ID") ON DELETE CASCADE
);

-- 17. Donation (후원) 테이블
CREATE TABLE "Donation"
(
    "DONATION_ID" BIGSERIAL   NOT NULL,
    "USER_ID"     BIGINT      NOT NULL,
    "AMOUNT"      BIGINT      NOT NULL,
    "TYPE"        VARCHAR(20) NOT NULL CHECK ("TYPE" IN ('REGULAR', 'ONE_TIME')),
    "STATUS"      VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK ("STATUS" IN ('PENDING', 'COMPLETED', 'FAILED')),
    "CREATED_AT"  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("DONATION_ID"),
    CONSTRAINT "FK_User_TO_Donation" FOREIGN KEY ("USER_ID")
        REFERENCES "User" ("USER_ID")
);

-- 18. Notification (알림) 테이블
CREATE TABLE "Notification"
(
    "NOTIFICATION_ID" BIGSERIAL   NOT NULL,
    "USER_ID"         BIGINT      NOT NULL,
    "TYPE"            VARCHAR(50) NOT NULL,
    "MESSAGE"         TEXT        NOT NULL,
    "IS_READ"         BOOLEAN     NOT NULL DEFAULT FALSE,
    "CREATED_AT"      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("NOTIFICATION_ID"),
    CONSTRAINT "FK_User_TO_Notification" FOREIGN KEY ("USER_ID")
        REFERENCES "User" ("USER_ID") ON DELETE CASCADE
);

-- 19. Sheet (악보/자료실) 테이블
CREATE TABLE "Sheet"
(
    "SHEET_ID"   BIGSERIAL    NOT NULL,
    "USER_ID"    BIGINT       NOT NULL,
    "FILE_KEY"   VARCHAR(255) NOT NULL,
    "FILE_NAME"  VARCHAR(200) NOT NULL,
    "IS_PUBLIC"  BOOLEAN      NOT NULL DEFAULT FALSE,
    "CREATED_AT" TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMPTZ NULL,
    "DELETED_AT" TIMESTAMPTZ NULL,
    PRIMARY KEY ("SHEET_ID"),
    UNIQUE ("FILE_KEY"),
    CONSTRAINT "FK_User_TO_Sheet" FOREIGN KEY ("USER_ID")
        REFERENCES "User" ("USER_ID")
);

-- 20. PracticeSchedule (연습 일정) 테이블
CREATE TABLE "PracticeSchedule"
(
    "SCHEDULE_ID" BIGSERIAL    NOT NULL,
    "USER_ID"     BIGINT       NOT NULL,
    "TITLE"       VARCHAR(200) NOT NULL,
    "DATE"        TIMESTAMPTZ  NOT NULL,
    "LOCATION"    VARCHAR(200) NOT NULL,
    "DESCRIPTION" TEXT NULL,
    "CREATED_AT"  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT"  TIMESTAMPTZ NULL,
    PRIMARY KEY ("SCHEDULE_ID"),
    CONSTRAINT "FK_User_TO_PracticeSchedule" FOREIGN KEY ("USER_ID")
        REFERENCES "User" ("USER_ID")
);

-- 21. ActivityMaterial (활동 자료) 테이블
CREATE TABLE "ActivityMaterial"
(
    "MATERIAL_ID" BIGSERIAL    NOT NULL,
    "USER_ID"     BIGINT       NOT NULL,
    "TITLE"       VARCHAR(200) NOT NULL,
    "FILE_KEY"    VARCHAR(255) NOT NULL,
    "FILE_NAME"   VARCHAR(200) NOT NULL,
    "DESCRIPTION" TEXT NULL,
    "CREATED_AT"  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT"  TIMESTAMPTZ NULL,
    "DELETED_AT"  TIMESTAMPTZ NULL,
    PRIMARY KEY ("MATERIAL_ID"),
    UNIQUE ("FILE_KEY"),
    CONSTRAINT "FK_User_TO_ActivityMaterial" FOREIGN KEY ("USER_ID")
        REFERENCES "User" ("USER_ID")
);