-- 파일 크기 컬럼 추가
ALTER TABLE "GalleryMedia"
    ADD COLUMN "FILE_SIZE" BIGINT NULL;

ALTER TABLE "NoticeImage"
    ADD COLUMN "FILE_SIZE" BIGINT NULL;

ALTER TABLE "PostImage"
    ADD COLUMN "FILE_SIZE" BIGINT NULL;

ALTER TABLE "Sheet"
    ADD COLUMN "FILE_SIZE" BIGINT NULL;

ALTER TABLE "ActivityMaterial"
    ADD COLUMN "FILE_SIZE" BIGINT NULL;